### ISSUE TITLE
False ID Mismatch Parse Error

### ISSUE THREAD

**Issue by theaob** [aholinch/sgp4#1]
Hello, on line https://github.com/aholinch/sgp4/blob/3ea6eaf1d0729cc602195ecdd100566f8c44333a/src/java/TLE.java#L270 the comparison was made with != but it should be .equals() because it is a string. This comparison flags a false parse error.

**Comment by aholinch** [comment]
Thank, you.  I made this mistake when converting objectID from an int to a String.

**Comment by aholinch** [comment]
I've changed it to .equals().  There is still more work to be done to support the full Alpha 5 convention but the false parse error should be gone for now.
